### ISSUE TITLE
SIA-R74 requires non-fixed units but does not consider reflow

### ISSUE THREAD

**Issue by offsetChris** [Siteimprove/alfa#755] opened 2021-03-26 20:30 UTC
Hello,

This came up a few times when utilizing this check, it seems this requires all font-size declarations to be using non-fixed units (ems, rems, etc). But simply using pixels for instance doesn't seem to fail the success criterion, it asks in the guidance documents to not interfere with the user agent's reflow OR use relative units. 

Digging further into the understandings document: 

> The scaling of content is primarily a user agent responsibility. User agents that satisfy UAAG 1.0 Checkpoint 4.1 allow users to configure text scale. The author's responsibility is to create Web content that does not prevent the user agent from scaling the content and that allows the reflow of the content within the current width of the viewport. 

There are very ancient browsers that would not support this, but I can't imagine we need to write the rules for browsers that are no longer supported by the companies that built them (IE6 for instance that is referenced in a few places in the guidance documents). 

Looking at pages with failures of this check, zooming in with browsers, extensions, and injecting larger font sizes with style sheets all make the content reflow and no actual disruption of the content occurs - I do not have to scroll horizontally, nothing is clipped and the container elements are resizing as expected. I'm unclear as to why this is still a failure. 

Happy to discuss further, just bringing it to your attention that this is coming up as a very common error that is not clear for users. And converting all websites to ems/rems isn't really practical if they are using media queries etc for a responsive layout.

**Comment by kasperisager** [comment] 2021-03-27 11:52
Thanks a ton for the input! The crux of the issue is that fixed font sizes break the ability to adjust the root text scale and have this cascade to the rest of the document. Consider the following document:

```html
<!DOCTYPE html>

<style>
  p {
    font-size: 18px;
  }
</style>

<p>Hello world</p>
```

In Chrome, a user can set their desired text scale at chrome://settings/fonts. What this effectively does is adjust the font size of the root element like this:

```css
:root {
  font-size: 32px; // 200% of the default 16px
}
```

However, as the `<p>` element from before uses a fixed font size, the increased text scale will have no effect, breaking the ability of the user to increase the text scale and therefore the ability to resize text to 200% without use of assistive technology, as required by WCAG.

Yes, the user could of course just use zoom. They could also just use Firefox, which will override the actual rendering of the text when increasing the text scale. In Chrome, however, this is an issue for users who rely on an increased text scale and we see that as a valid reason for flagging it.

**Comment by kasperisager** [comment] 2021-03-27 11:58
MDN specifically calls out this issue as well:

> Defining font sizes in `px` is _not accessible_, because the user cannot change the font size in some browsers. For example, users with limited vision may wish to set the font size much larger than the size chosen by a web designer. Avoid using them for font sizes if you wish to create an inclusive design.

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#pixels

**Comment by offsetChris** [comment] 2021-03-30 17:12
Thanks @kasperisager ! That makes sense, however it is concerning that this rule seems to be an 'only Chrome' problem. Future iterations of the browser could (should? are doing so?) resolve this and utilizing font size as px becomes equally adaptable. Are we suggesting that all websites need to retrofit their legacy away from pixels because one browser doesn't accommodate that technology? That is going to be a hard sell for anyone with a legacy system that was built on pixels before ems/rems became available.

**Comment by offsetChris** [comment] 2021-03-30 18:00
Reading the text of the check too, I had assumed this referred to zooming which when checking the page manually did not have an issue so there seemed to be a discrepancy between manually checking this, vs the automated check. That might be too granular to specify the testing operation here, but since this is a one feature/one browser failure I'm not sure how that might be communicated.

**Comment by kasperisager** [comment] 2021-04-13 10:14
Closing as this is working as intended.

**Closed by kasperisager** 2021-04-13 10:14 UTC
Labels: bug
