### ISSUE TITLE
R73 fails a paragraph, but reason is not clear

### ISSUE THREAD

**Issue by jrpool** [Siteimprove/alfa#1229] opened 2022-09-25 14:32 UTC
R73 fails the first paragraph (with the text content “Home”) in the body of the document at [https://jpdev.pro/jpdev/cv/index.html](https://jpdev.pro/jpdev/cv/index.html.) I see nothing that explains that reported failure.

**Comment by Jym77** [comment] 2022-09-26 09:09
Hi @jrpool, thanks for the message.

---
Why we flag it?

The initial value of `line-height` is `normal`, which result in a used value generally around 1.2, which is below the 1.5 WCAG recommandation.

---
Why this is maybe a false positive?

Of course, in this case there is a single word, so also a single line, and the line height is pointless (or rather needs to be combined with the inter-paragraph spacing). In any case, it does not corresponds to WCAG's definition of [block of text](https://www.w3.org/TR/WCAG/#dfn-blocks-of-text) that is used in 1.4.8… So the SC does not apply and this is not a WCAG failure…

---
Why this is maybe not that much a false positive?

For lack of layout system, Alfa cannot really detect if a text will be spread on several lines or not 😞 
The heuristic for this rule (and a few others) is to consider that elements with a role of `paragraph` (as defined in ARIA 1.2) are used for WCAG's "blocks of text". This corresponds to the [first assumption](https://alfa.siteimprove.com/rules/sia-r73#assumptions) in the rule.

I would challenge a bit the use of a `<p>` element (and a role of `paragraph`) for a single word. ARIA isn't really helping on that as it defines the role as "A paragraph of content." But the [HTML specs](https://html.spec.whatwg.org/multipage/dom.html#paragraph) are a bit more explicit:
> A paragraph is typically a run of [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2) that forms a block of text with one or more sentences that discuss a particular topic, as in typography, but can also be used for more general thematic grouping.

I would argue that a single word does not match this definition and therefore should not be used alone in a `<p>` element (a `<div>` would be more appropriate). And if using a `<p>` element, I also feel its role should be changed from `paragraph`. 

In any case, having a role of `paragraph` for something that is not a WCAG "block of text" does break the assumption of the rule, and we know it will then provide inaccurate outcomes, as in this case. It is a problem we do see here and there. So far, not enough to make us reconsider this choice and improve the heuristic.

---
As a conclusion.

We are aware of this problem. While it is technically a false positive, this also corresponds to an arguably incorrect use of HTML elements and ARIA roles. The rule tries to handle that with an assumption which we see not holding in a few cases, but not yet enough to try and strengthen it.

**Comment by jrpool** [comment] 2022-09-26 16:55
@Jym77: Thank you for your detailed and helpful reply to this issue.

You raise a valuable question about whether it is semantically appropriate to enclose a single word in a `p` element. If we accept your argument that this is typically dubious, then I am still having trouble with the behavior of alfa:

1. Turning the single word in this case into a long sentence does not cause any clipping or overlap in Chrome with zoom up to 500% or with Chrome's Very Large font setting. Everything gets enlarged proportionally. So it looks as if the complaint of R73 is the wrong complaint, because the problem with the line height is not related to the font size; the problem is simply the fact that the line height is less than 1.5.
2. The paragraph in question is outside the `main` landmark, so perhaps it should be treated as not subject to a norm that applies to main paragraph text.

**Comment by Jym77** [comment] 2022-09-27 08:25
Hi,
R73 is not about clipping text, it checks the following bit of 1.4.8:
> For the visual presentation of [blocks of text](https://www.w3.org/TR/WCAG/#dfn-blocks-of-text), a [mechanism](https://www.w3.org/TR/WCAG/#dfn-mechanism) is available to achieve the following:
> (…)
> * Line spacing (leading) is at least space-and-a-half within paragraphs, and paragraph spacing is at least 1.5 times larger than the line spacing.

It's not clear that user styles are a way to satisfy it, which is why Alfa flags small `line-height`. The rule also assumes there is no mechanism in the page to change the spacing (something Alfa cannot really test). I'm not fully sure that user styles can be considered as a mechanism to satisfy 1.4.8 🤔 

In the second example of [F88](https://www.w3.org/WAI/WCAG21/Techniques/failures/F88), there is a `p { text-align: justify }` style which can be overriden with an `!important` user style, so it sounds like user style is not a valid solution here… There is no similar failure technique for the "line spacing".

**Comment by Jym77** [comment] 2022-11-21 10:30
@jrpool I feel Alfa here is working as intended and I'm closing this.

Feel free to re-open if you think we need more discussion on it.

**Closed by Jym77** 2022-11-21 10:30 UTC
Labels: bug
